import React, { useState } from 'react';
import { 
  GraduationCap, 
  BookOpen, 
  CheckCircle2, 
  Circle, 
  Code, 
  Sparkles, 
  Terminal, 
  Copy, 
  Check, 
  Layers, 
  ShieldCheck,
  ChevronRight
} from 'lucide-react';
import { LessonItem } from '../types';
import { AudioLessonPlayer } from './AudioLessonPlayer';

interface AILearningAcademyProps {
  claudeLessons: LessonItem[];
  kiroLessons: LessonItem[];
}

export const AILearningAcademy: React.FC<AILearningAcademyProps> = ({
  claudeLessons,
  kiroLessons,
}) => {
  const [activeSeries, setActiveSeries] = useState<'claude' | 'kiro' | 'gemini'>('claude');
  const [selectedLessonId, setSelectedLessonId] = useState<string>('');
  const [completedLessons, setCompletedLessons] = useState<Record<string, boolean>>(() => {
    try {
      const saved = localStorage.getItem('learn_better_completed_lessons');
      return saved ? JSON.parse(saved) : {};
    } catch {
      return {};
    }
  });
  const [copiedPromptIndex, setCopiedPromptIndex] = useState<number | null>(null);

  const currentLessons = activeSeries === 'claude' ? claudeLessons : kiroLessons;
  const activeLesson = currentLessons.find(l => l.id === selectedLessonId) || currentLessons[0];

  const toggleLessonCompletion = (id: string) => {
    setCompletedLessons(prev => {
      const next = { ...prev, [id]: !prev[id] };
      localStorage.setItem('learn_better_completed_lessons', JSON.stringify(next));
      return next;
    });
  };

  const handleCopyText = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedPromptIndex(index);
    setTimeout(() => setCopiedPromptIndex(null), 2000);
  };

  // Gemini Vibe Coding Curriculum (Synthesized from the repo's lessons + modern agentic paradigms)
  const geminiCurriculum = [
    {
      title: 'Module 1: The Contract-First Vibe Coding Mindset',
      description: 'Why you should never say "build me an app" without specifying input/output boundaries, deterministic schemas, and verification commands.',
      corePrinciples: [
        'Deterministic schemas (JSON/Markdown) anchor multiple assistants.',
        'File isolation: Always mandate new folders for new code experiments.',
        'Verify before progressing: Every step must end with an actionable check.',
      ],
      suggestedPrompt: `You are collaborating on the learn-better repository. We need a new feature: [Describe Feature].
Constraints:
1. Place all new code in a dedicated new folder /webapp/. Do not edit existing python files.
2. Return code in TypeScript with full strict typing.
3. Provide a one-line terminal command to verify the compilation.`,
    },
    {
      title: 'Module 2: Managing Context Windows & Daily Free Quotas',
      description: 'Techniques to achieve massive software output while staying well within daily free token limits on Gemini Flash or Claude.',
      corePrinciples: [
        'Never paste entire codebases: reference file paths and line ranges.',
        'Record chronological verbatim prompt logs (gemini_prompts.md) to resume sessions instantly.',
        'Micro-sprints: 1 prompt = 1 verifiable outcome, rather than 10 ambiguous features in a monolithic block.',
      ],
      suggestedPrompt: `Review only the function parsePlaylists in src/services/api.ts. 
Optimize the error handling for invalid YouTube playlist URLs. 
Do not rewrite unrelated files.`,
    },
    {
      title: 'Module 3: Multi-AI Orchestration (Kiro + Claude + Gemini)',
      description: 'How to divide work cleanly among different AI models according to their architectural sweet spots.',
      corePrinciples: [
        'Kiro: Fast CLI scripting, local Python runners (yt-dlp, faster-whisper, Piper TTS).',
        'Claude: Pedagogical tutorials, markdown documentation, deep architecture design.',
        'Gemini: High-speed reasoning, responsive React/Vite frontends, large-context synthesis.',
      ],
      suggestedPrompt: `We have generated transcript data in data/transcripts/*.txt. 
Write a script that reads these files and outputs a clean JSON knowledge graph.`,
    },
    {
      title: 'Module 4: Safe Git Sync & Upstream Contribution',
      description: 'How to safely bring code generated by AI coding agents back into your GitHub repository without git conflicts or lost history.',
      corePrinciples: [
        'Always create a feature branch before merging agent code.',
        'Inspect git status to guarantee legacy scripts were untouched.',
        'Use squash commits or clean PRs to keep the repository history clean.',
      ],
      suggestedPrompt: `git checkout -b feature/gemini-knowledge-hub
git add webapp/ gemini_prompts.md gemini_feedback.md
git status
git commit -m "Add Gemini Knowledge Hub webapp and AI vibe coding guide"`,
    },
  ];

  return (
    <div className="space-y-6">
      {/* Academy Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <GraduationCap className="w-5 h-5 text-sky-400" />
            <h1 className="text-xl font-bold text-white">AI Vibe Coding Academy</h1>
            <span className="text-[11px] font-semibold px-2 py-0.5 rounded bg-sky-950 text-sky-300 border border-sky-800">
              Steer & Verify
            </span>
          </div>
          <p className="text-sm text-slate-400 mt-1">
            Reconstruct real software and master the art of collaborating with AI coding assistants.
          </p>
        </div>

        {/* Series Switcher */}
        <div className="flex items-center gap-1.5 bg-slate-950 p-1 rounded-lg border border-slate-800 text-xs">
          <button
            onClick={() => { setActiveSeries('claude'); setSelectedLessonId(''); }}
            className={`px-3 py-1.5 rounded-md font-medium transition-colors ${
              activeSeries === 'claude' ? 'bg-sky-600 text-white' : 'text-slate-400 hover:text-white'
            }`}
          >
            Claude Series ({claudeLessons.length})
          </button>
          <button
            onClick={() => { setActiveSeries('kiro'); setSelectedLessonId(''); }}
            className={`px-3 py-1.5 rounded-md font-medium transition-colors ${
              activeSeries === 'kiro' ? 'bg-sky-600 text-white' : 'text-slate-400 hover:text-white'
            }`}
          >
            Kiro Series ({kiroLessons.length})
          </button>
          <button
            onClick={() => setActiveSeries('gemini')}
            className={`px-3 py-1.5 rounded-md font-medium transition-colors flex items-center gap-1 ${
              activeSeries === 'gemini' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
            }`}
          >
            <Sparkles className="w-3 h-3 text-amber-400" />
            Gemini Playbook
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      {activeSeries === 'gemini' ? (
        /* Gemini Vibe Coding Masterclass */
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {geminiCurriculum.map((mod, idx) => (
            <div key={idx} className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3.5 flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold px-2 py-0.5 rounded bg-indigo-950 text-indigo-300 border border-indigo-800">
                    Rule #{idx + 1}
                  </span>
                  <span className="text-xs text-slate-500">Gemini 2.5 Paradigm</span>
                </div>
                <h3 className="text-base font-bold text-white mt-2">{mod.title}</h3>
                <p className="text-xs text-slate-400 mt-1 leading-relaxed">{mod.description}</p>

                <div className="mt-3 space-y-1.5">
                  <h4 className="text-[11px] font-semibold text-slate-300 uppercase tracking-wider">
                    Core Principles:
                  </h4>
                  <ul className="text-xs text-slate-400 space-y-1 list-disc list-inside">
                    {mod.corePrinciples.map((cp, cIdx) => (
                      <li key={cIdx}>{cp}</li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="pt-3 border-t border-slate-800">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[11px] font-semibold text-sky-400">Template Prompt:</span>
                  <button
                    onClick={() => handleCopyText(mod.suggestedPrompt, idx)}
                    className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-white"
                  >
                    {copiedPromptIndex === idx ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    {copiedPromptIndex === idx ? 'Copied' : 'Copy'}
                  </button>
                </div>
                <pre className="p-2.5 rounded bg-slate-950 border border-slate-850 text-[11px] text-slate-300 font-mono whitespace-pre-wrap leading-relaxed">
                  {mod.suggestedPrompt}
                </pre>
              </div>
            </div>
          ))}
        </div>
      ) : (
        /* Claude or Kiro Interactive Lessons Browser */
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Lessons List Navigator */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col h-[740px]">
            <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
              {activeSeries === 'claude' ? 'Claude Lessons' : 'Kiro Lessons'}
            </h3>

            <div className="flex-1 overflow-y-auto space-y-1.5 pr-1 scrollbar-thin">
              {currentLessons.map((lesson) => {
                const isSelected = activeLesson?.id === lesson.id;
                const isDone = completedLessons[lesson.id];
                return (
                  <button
                    key={lesson.id}
                    onClick={() => setSelectedLessonId(lesson.id)}
                    className={`w-full text-left p-2.5 rounded-lg border text-xs transition-all flex items-start gap-2.5 ${
                      isSelected
                        ? 'bg-sky-950/60 border-sky-700 text-white'
                        : 'bg-slate-950/50 border-slate-800/80 text-slate-300 hover:bg-slate-800/60'
                    }`}
                  >
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        toggleLessonCompletion(lesson.id);
                      }}
                      className="mt-0.5 text-slate-500 hover:text-emerald-400"
                    >
                      {isDone ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      ) : (
                        <Circle className="w-4 h-4" />
                      )}
                    </button>

                    <div className="flex-1 min-w-0">
                      <div className="font-medium truncate">{lesson.title}</div>
                      <div className="text-[11px] text-slate-500 truncate mt-0.5">
                        {lesson.filename}
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Lesson Content Viewer */}
          <div className="lg:col-span-3 bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-between">
            {activeLesson ? (
              <div className="space-y-4">
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <div>
                    <span className="text-xs font-semibold px-2 py-0.5 rounded bg-sky-950 text-sky-300 border border-sky-800">
                      {activeLesson.series} Series &bull; {activeLesson.filename}
                    </span>
                    <h2 className="text-lg font-bold text-white mt-1.5">{activeLesson.title}</h2>
                  </div>

                  <button
                    onClick={() => toggleLessonCompletion(activeLesson.id)}
                    className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg border transition-colors ${
                      completedLessons[activeLesson.id]
                        ? 'bg-emerald-950/80 text-emerald-300 border-emerald-700'
                        : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
                    }`}
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    {completedLessons[activeLesson.id] ? 'Completed' : 'Mark Complete'}
                  </button>
                </div>

                {/* Audio Playback Controls for AirPods & Speakers */}
                <AudioLessonPlayer lesson={activeLesson} />

                {/* Lesson Markdown Reader */}
                <div className="bg-slate-950 p-5 rounded-xl border border-slate-800 max-h-[580px] overflow-y-auto">
                  <pre className="whitespace-pre-wrap font-sans text-xs text-slate-300 leading-relaxed">
                    {activeLesson.content}
                  </pre>
                </div>
              </div>
            ) : (
              <div className="text-center py-24 text-slate-500 text-xs">
                Select a lesson on the left to read.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
