import React, { useState } from 'react';
import { 
  BrainCircuit, 
  Sparkles, 
  BookOpen, 
  Download, 
  Plus, 
  HelpCircle, 
  Lightbulb, 
  Copy, 
  Check, 
  FileDown, 
  Layers,
  Search,
  Trash2
} from 'lucide-react';
import { YouTubeClip, SummaryData } from '../types';

interface KnowledgeHubProps {
  clips: YouTubeClip[];
  summaries: SummaryData[];
  selectedClip: YouTubeClip | null;
  onSelectClip: (clip: YouTubeClip) => void;
  onUpdateClipNotes: (clipId: string, notes: string) => void;
  onAddQuestion: (clipId: string, question: string) => void;
  onDeleteQuestion: (clipId: string, index: number) => void;
  onAddIdea: (clipId: string, idea: string) => void;
  onDeleteIdea: (clipId: string, index: number) => void;
  onNavigateToGemini: (clip: YouTubeClip, content: string) => void;
}

export const KnowledgeHub: React.FC<KnowledgeHubProps> = ({
  clips,
  summaries,
  selectedClip,
  onSelectClip,
  onUpdateClipNotes,
  onAddQuestion,
  onDeleteQuestion,
  onAddIdea,
  onDeleteIdea,
  onNavigateToGemini,
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeNoteText, setActiveNoteText] = useState(selectedClip?.notes || '');
  const [newQuestionInput, setNewQuestionInput] = useState('');
  const [newIdeaInput, setNewIdeaInput] = useState('');
  const [copied, setCopied] = useState(false);
  const [activeView, setActiveView] = useState<'editor' | 'mindmap' | 'summary'>('editor');

  // When selected clip changes, update local state
  React.useEffect(() => {
    setActiveNoteText(selectedClip?.notes || '');
  }, [selectedClip?.id]);

  const currentClip = selectedClip || clips[0];
  const matchingSummary = currentClip ? summaries.find(s => s.videoId === currentClip.id) : null;

  const handleSaveNotes = () => {
    if (!currentClip) return;
    onUpdateClipNotes(currentClip.id, activeNoteText);
  };

  const handleAddQuestionSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newQuestionInput.trim() || !currentClip) return;
    onAddQuestion(currentClip.id, newQuestionInput.trim());
    setNewQuestionInput('');
  };

  const handleAddIdeaSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newIdeaInput.trim() || !currentClip) return;
    onAddIdea(currentClip.id, newIdeaInput.trim());
    setNewIdeaInput('');
  };

  // Generate Obsidian-compatible Markdown
  const generateObsidianMarkdown = (): string => {
    if (!currentClip) return '';
    const dateStr = new Date().toISOString().split('T')[0];
    const tagsList = currentClip.tags.map(t => `#${t.toLowerCase()}`).join(' ');

    return `---
title: "${currentClip.title}"
source: "https://www.youtube.com/watch?v=${currentClip.id}"
channel: "${currentClip.channel}"
status: "${currentClip.status}"
date: "${dateStr}"
tags: [${currentClip.tags.map(t => `"${t}"`).join(', ')}]
---

# ${currentClip.title}

> [!info] Video Details
> - **Channel**: ${currentClip.channel}
> - **Video Link**: [Watch on YouTube](https://www.youtube.com/watch?v=${currentClip.id})
> - **Status**: ${currentClip.status}
> - **Tags**: ${tagsList}

## 💡 Key Takeaways & Summaries
${matchingSummary ? matchingSummary.oneLineTakeaway : 'Extracted directly via Learn-Better knowledge hub.'}

## 📝 Personal Notes & Reflections
${currentClip.notes || '*No notes recorded yet.*'}

## ❓ Questions & Inquiries
${(currentClip.userQuestions && currentClip.userQuestions.length > 0)
  ? currentClip.userQuestions.map(q => `- [ ] ${q}`).join('\n')
  : '- *No active questions.*'}

## 🚀 Prompts & AI Vibe Coding Ideas
${(currentClip.userIdeas && currentClip.userIdeas.length > 0)
  ? currentClip.userIdeas.map(i => `- 💡 ${i}`).join('\n')
  : '- *No ideas recorded yet.*'}

---
*Generated by Learn Better Knowledge Hub & Gemini Studio*
`;
  };

  const handleExportObsidian = () => {
    const md = generateObsidianMarkdown();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${currentClip.title.replace(/[^a-zA-Z0-9_-]/g, '_')}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopyToClipboard = () => {
    const md = generateObsidianMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const filteredClips = clips.filter(c => 
    c.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.channel.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <BrainCircuit className="w-5 h-5 text-indigo-400" />
            Personal Knowledge Hub
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Consolidate key takeaways, record questions, draft AI prompts, and export Obsidian-ready study notes.
          </p>
        </div>

        {currentClip && (
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={handleCopyToClipboard}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied MD' : 'Copy Markdown'}
            </button>
            <button
              onClick={handleExportObsidian}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg transition-colors"
            >
              <FileDown className="w-3.5 h-3.5 text-sky-400" />
              Obsidian Export (.md)
            </button>
            <button
              onClick={() => onNavigateToGemini(currentClip, matchingSummary ? matchingSummary.content : (currentClip.notes || currentClip.title))}
              className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 rounded-lg transition-colors shadow-sm"
            >
              <Sparkles className="w-3.5 h-3.5 text-amber-300" />
              Gemini Distill
            </button>
          </div>
        )}
      </div>

      {/* Main Grid: Clip Selector Sidebar + Knowledge Workspace */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Left: Clips Navigator */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col h-[740px]">
          <div className="mb-3">
            <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
              Select Study Clip ({clips.length})
            </h3>
            <div className="relative">
              <Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5 text-slate-500" />
              <input
                type="text"
                placeholder="Search clips..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-8 pr-2.5 py-1.5 text-xs bg-slate-950 border border-slate-800 rounded-lg text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="flex-1 overflow-y-auto space-y-2 pr-1 scrollbar-thin">
            {filteredClips.map((clip) => {
              const isSelected = currentClip?.id === clip.id;
              const hasRepoSummary = summaries.some(s => s.videoId === clip.id);
              return (
                <button
                  key={clip.id}
                  onClick={() => onSelectClip(clip)}
                  className={`w-full text-left p-2.5 rounded-lg border text-xs transition-all ${
                    isSelected
                      ? 'bg-indigo-950/60 border-indigo-700 text-white shadow-sm'
                      : 'bg-slate-950/50 border-slate-800/80 text-slate-300 hover:bg-slate-800/60'
                  }`}
                >
                  <div className="font-medium line-clamp-2 leading-snug mb-1">
                    {clip.title}
                  </div>
                  <div className="flex items-center justify-between text-[11px] text-slate-400">
                    <span className="truncate max-w-[120px]">{clip.channel}</span>
                    {hasRepoSummary && (
                      <span className="text-[10px] px-1.5 py-0.2 rounded bg-indigo-900/80 text-indigo-300">
                        Summary
                      </span>
                    )}
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Right: Active Knowledge Canvas */}
        <div className="lg:col-span-3 space-y-4">
          {currentClip ? (
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-5">
              {/* Title & View Switcher */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-800 gap-3">
                <div>
                  <span className="text-xs font-medium text-indigo-400">Knowledge File &bull; {currentClip.channel}</span>
                  <h2 className="text-lg font-bold text-white mt-0.5">{currentClip.title}</h2>
                </div>

                <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-lg border border-slate-800 text-xs">
                  <button
                    onClick={() => setActiveView('editor')}
                    className={`px-3 py-1 rounded font-medium transition-colors ${
                      activeView === 'editor' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Notes & Questions
                  </button>
                  <button
                    onClick={() => setActiveView('summary')}
                    className={`px-3 py-1 rounded font-medium transition-colors ${
                      activeView === 'summary' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Repo Summary
                  </button>
                  <button
                    onClick={() => setActiveView('mindmap')}
                    className={`px-3 py-1 rounded font-medium transition-colors ${
                      activeView === 'mindmap' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Concept Map
                  </button>
                </div>
              </div>

              {/* View 1: Personal Notes, Questions, and Ideas */}
              {activeView === 'editor' && (
                <div className="space-y-6">
                  {/* Notes Editor */}
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                        <BookOpen className="w-4 h-4 text-sky-400" />
                        My Personal Notes & Insights
                      </label>
                      <button
                        onClick={handleSaveNotes}
                        className="text-xs text-sky-400 hover:text-sky-300 font-semibold"
                      >
                        Save Notes
                      </button>
                    </div>
                    <textarea
                      rows={5}
                      value={activeNoteText}
                      onChange={(e) => setActiveNoteText(e.target.value)}
                      onBlur={handleSaveNotes}
                      placeholder="Write your personal reflections, key findings, takeaways, or bullet points here..."
                      className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500 leading-relaxed font-mono"
                    ></textarea>
                    <p className="text-[11px] text-slate-500 mt-1">
                      Auto-saves when clicking outside. Markdown formatted.
                    </p>
                  </div>

                  {/* Two Columns: Questions & Prompts/Ideas */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5 pt-2">
                    {/* Column 1: Questions & Doubts */}
                    <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800 space-y-3">
                      <div className="flex items-center justify-between">
                        <h4 className="text-xs font-semibold text-amber-300 flex items-center gap-1.5">
                          <HelpCircle className="w-4 h-4 text-amber-400" />
                          Questions & Unresolved Doubts
                        </h4>
                        <span className="text-[11px] text-slate-500">
                          {currentClip.userQuestions?.length || 0}
                        </span>
                      </div>

                      <form onSubmit={handleAddQuestionSubmit} className="flex gap-1.5">
                        <input
                          type="text"
                          placeholder="Ask a question about this clip..."
                          value={newQuestionInput}
                          onChange={(e) => setNewQuestionInput(e.target.value)}
                          className="flex-1 bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-amber-500"
                        />
                        <button
                          type="submit"
                          className="px-2.5 py-1.5 bg-amber-600 hover:bg-amber-500 text-white rounded-lg text-xs"
                        >
                          <Plus className="w-3.5 h-3.5" />
                        </button>
                      </form>

                      <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                        {currentClip.userQuestions && currentClip.userQuestions.length > 0 ? (
                          currentClip.userQuestions.map((q, idx) => (
                            <div
                              key={idx}
                              className="flex items-start justify-between gap-2 p-2 rounded-lg bg-slate-900/90 border border-slate-800 text-xs text-slate-300"
                            >
                              <span className="leading-relaxed">{q}</span>
                              <button
                                onClick={() => onDeleteQuestion(currentClip.id, idx)}
                                className="text-slate-500 hover:text-rose-400 mt-0.5"
                                title="Delete question"
                              >
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          ))
                        ) : (
                          <p className="text-xs text-slate-500 italic py-2 text-center">
                            No questions logged yet. Add concepts you want to clarify.
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Column 2: Ideas & Vibe Prompts */}
                    <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800 space-y-3">
                      <div className="flex items-center justify-between">
                        <h4 className="text-xs font-semibold text-emerald-300 flex items-center gap-1.5">
                          <Lightbulb className="w-4 h-4 text-emerald-400" />
                          Coding Ideas & Target Prompts
                        </h4>
                        <span className="text-[11px] text-slate-500">
                          {currentClip.userIdeas?.length || 0}
                        </span>
                      </div>

                      <form onSubmit={handleAddIdeaSubmit} className="flex gap-1.5">
                        <input
                          type="text"
                          placeholder="e.g. Build a script that tests this..."
                          value={newIdeaInput}
                          onChange={(e) => setNewIdeaInput(e.target.value)}
                          className="flex-1 bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-emerald-500"
                        />
                        <button
                          type="submit"
                          className="px-2.5 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs"
                        >
                          <Plus className="w-3.5 h-3.5" />
                        </button>
                      </form>

                      <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                        {currentClip.userIdeas && currentClip.userIdeas.length > 0 ? (
                          currentClip.userIdeas.map((idea, idx) => (
                            <div
                              key={idx}
                              className="flex items-start justify-between gap-2 p-2 rounded-lg bg-slate-900/90 border border-slate-800 text-xs text-slate-300"
                            >
                              <span className="leading-relaxed">{idea}</span>
                              <button
                                onClick={() => onDeleteIdea(currentClip.id, idx)}
                                className="text-slate-500 hover:text-rose-400 mt-0.5"
                                title="Delete idea"
                              >
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          ))
                        ) : (
                          <p className="text-xs text-slate-500 italic py-2 text-center">
                            No prompts or ideas saved yet.
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* View 2: Repository Summary (From data/summaries/*.md) */}
              {activeView === 'summary' && (
                <div className="space-y-4">
                  {matchingSummary ? (
                    <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-xs space-y-3 leading-relaxed">
                      <div className="flex items-center justify-between pb-2 border-b border-slate-800">
                        <span className="text-slate-400">Source: <strong className="text-slate-200">{matchingSummary.filename}</strong></span>
                        {matchingSummary.approxLength && (
                          <span className="px-2 py-0.5 rounded bg-slate-800 text-slate-300 text-[11px]">
                            {matchingSummary.approxLength}
                          </span>
                        )}
                      </div>
                      <pre className="whitespace-pre-wrap font-sans text-slate-300 text-xs leading-relaxed max-h-[500px] overflow-y-auto p-3 bg-slate-900 rounded-lg border border-slate-800">
                        {matchingSummary.content}
                      </pre>
                    </div>
                  ) : (
                    <div className="text-center py-10 bg-slate-950 rounded-xl border border-slate-800">
                      <BookOpen className="w-8 h-8 text-slate-600 mx-auto mb-2" />
                      <p className="text-xs text-slate-400">
                        No pre-compiled summary found in <code className="text-sky-400">data/summaries/</code> for this video ID ({currentClip.id}).
                      </p>
                      <button
                        onClick={() => onNavigateToGemini(currentClip, currentClip.title)}
                        className="mt-3 px-3 py-1.5 text-xs font-semibold rounded bg-indigo-600 text-white hover:bg-indigo-500"
                      >
                        Generate Summary with Gemini
                      </button>
                    </div>
                  )}
                </div>
              )}

              {/* View 3: Concept / Mind Map */}
              {activeView === 'mindmap' && (
                <div className="space-y-4">
                  <div className="bg-slate-950 p-6 rounded-xl border border-slate-800">
                    <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-4">
                      Knowledge Concept Clusters for {currentClip.title}
                    </h4>

                    <div className="flex flex-col items-center justify-center space-y-6 py-4">
                      {/* Root Node */}
                      <div className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-sky-600 text-white font-bold text-sm shadow-md border border-indigo-400/30">
                        {currentClip.title.length > 35 ? currentClip.title.slice(0, 35) + '...' : currentClip.title}
                      </div>

                      {/* Connection branch */}
                      <div className="w-0.5 h-6 bg-slate-700"></div>

                      {/* Child Clusters */}
                      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 w-full">
                        <div className="p-3 rounded-lg bg-slate-900 border border-indigo-900/60 space-y-1.5">
                          <h5 className="font-semibold text-indigo-300 text-xs flex items-center gap-1">
                            <Layers className="w-3.5 h-3.5" /> Core Concepts
                          </h5>
                          <ul className="text-[11px] text-slate-400 list-disc list-inside space-y-1">
                            {currentClip.tags.map(t => (
                              <li key={t}>{t}</li>
                            ))}
                          </ul>
                        </div>

                        <div className="p-3 rounded-lg bg-slate-900 border border-amber-900/60 space-y-1.5">
                          <h5 className="font-semibold text-amber-300 text-xs flex items-center gap-1">
                            <HelpCircle className="w-3.5 h-3.5" /> Inquiries
                          </h5>
                          <p className="text-[11px] text-slate-400">
                            {currentClip.userQuestions?.length ? `${currentClip.userQuestions.length} active questions logged` : 'No open questions'}
                          </p>
                        </div>

                        <div className="p-3 rounded-lg bg-slate-900 border border-emerald-900/60 space-y-1.5">
                          <h5 className="font-semibold text-emerald-300 text-xs flex items-center gap-1">
                            <Lightbulb className="w-3.5 h-3.5" /> Next Steps
                          </h5>
                          <p className="text-[11px] text-slate-400">
                            Status: <strong className="text-slate-200 capitalize">{currentClip.status}</strong>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-20 bg-slate-900 rounded-xl border border-slate-800">
              <p className="text-sm text-slate-400">Select a clip on the left to inspect its knowledge hub.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
